### ISSUE TITLE
Song Editor Grid

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#2] opened 2015-10-05 06:28 UTC
Digitizer and I have noticed that not all of the grids are consistant. For example, the song editor has an embossed stroke on the grid whereas other areas of the program have just a solid stroke style. We think that we should stick with just a solid grid that has good contast with the background, without being so bright that it is distracting for users.

I've @mentioned the coders that have volunteered to assist with coding for this theme. I know you're all busy, but if you have time, I would really appreciate some assistance on this.

@Umcaruje 
@tresf 
@diizy 
@Sti2nd

**Comment by tresf** [comment] 2015-11-13 15:48
@RebeccaDeField Please change the tile to "Song Editor Grid" to be more specific.

I can confirm that this embossed stroke is draw programatically.  The offending line(s) are here:

https://github.com/LMMS/lmms/blob/master/src/core/Track.cpp#L1043:L1047

Offending lines:

``` cpp
    pmp.setPen( QPen( QColor( 140, 140, 140, 64 ), 1 ) );
    for( float x = 1.0; x < w * 2; x += ppt )
    {
        pmp.drawLine( QLineF( x, 0.0, x, h ) );
    }
```

Removing this makes the grid all-but disappear since it then becomes gray on black, so this isn't recommended.

Unfortunately, the black line is drawn programatically too.  @michaelgregorius can I ask for your advise as to how to tackle this through CSS?

@Umcaruje @StakeoutPunch what are your opinions on removing the emboss in general?

![image](https://cloud.githubusercontent.com/assets/6345473/11149778/7b1bfc54-89f2-11e5-8935-5b8cc2f27e20.png)

Preview after change:

| Before | After |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/6345473/11150002/94a1237e-89f3-11e5-8073-30c0dd6080ee.png) | ![image](https://cloud.githubusercontent.com/assets/6345473/11149881/f5428a70-89f2-11e5-939e-54059f42b2ee.png) |

**Comment by tresf** [comment] 2015-11-13 18:25
Since the codebase already had most of the work done, I decided to go ahead and tackle this here.  Feedback needed prior to merging: https://github.com/LMMS/lmms/pull/2442

| Before | After |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/6345473/11150002/94a1237e-89f3-11e5-8073-30c0dd6080ee.png) | ![image](https://cloud.githubusercontent.com/assets/6345473/11153772/36cf18b2-8a09-11e5-91f7-3432499ab300.png) |

**Flattened CSS**

![image](https://cloud.githubusercontent.com/assets/6345473/11159072/91e75856-8a2a-11e5-9f27-0bf149e3873b.png)

**Comment by tresf** [comment] 2015-11-13 18:26
here: https://github.com/LMMS/lmms/pull/2442

**Comment by michaelgregorius** [comment] 2015-11-13 18:58
@tresf The pull request looks good to me!

I think we should even consider removing the gradient from the grid because to me it does not really communicate that you can put something in there because it "bulges out". An alternative might be to attach the grid elements to a CSS style as well (in case they are not already). That way you could have flat themes, round themes, etc. What do you think?

**Comment by tresf** [comment] 2015-11-13 22:21
>  we should even consider removing the gradient from the grid because to me it does not really communicate that you can put something in there because it "bulges out"

@michaelgregorius done via https://github.com/LMMS/lmms/commit/2869d53fec469024587d0641f183d142ca8f0e78

> An alternative might be to attach the grid elements to a CSS style as well (in case they are not already). That way you could have flat themes, round themes, etc. What do you think?

The thin white emboss line would be lost with the original commit, but the gradient was pure CSS in this case (no C++ changes), so we should be safe without code changes (in regards to the bulge-ness) so as long as we're ok loosing the thin white line emboss.  I can always code the thin white line emboss back in to and set 0 opacity if people want to keep it around.

**Flattened CSS**

![image](https://cloud.githubusercontent.com/assets/6345473/11159072/91e75856-8a2a-11e5-9f27-0bf149e3873b.png)

**Comment by tresf** [comment] 2015-11-13 22:21
![image](https://cloud.githubusercontent.com/assets/6345473/11159072/91e75856-8a2a-11e5-9f27-0bf149e3873b.png)

**Comment by Umcaruje** [comment] 2015-11-13 23:03
Well, if we are doing this, the patterns should be also gradient-less as well as the toolbars, imho.

**Comment by tresf** [comment] 2015-11-14 02:25
> Well, if we are doing this, the patterns should be also gradient-less as well as the toolbars, imho.

Fair enough.  Emboss is back via https://github.com/tresf/lmms/commit/aaa798c746023fa978ae1d30839191dc4d95c257.  This isn't about fixing `default`, it's about removing hard-coded values.  Once the build is finished, I'll post a screenshot and merge.

**Comment by tresf** [comment] 2015-11-14 02:45
Ok, here's the preview.  Merging.

![image](https://cloud.githubusercontent.com/assets/6345473/11161614/b74193ee-8a4f-11e5-8817-1a9c8383a2ab.png)

**Comment by tresf** [comment] 2015-11-14 02:48
@RebeccaDeField, merged. Please close this issue at your leisure (or have @HDDigitizerMusic grant us access to do so)

This is now fully functional on master branch via:

``` css
/* Flat Song Editor Background */
TrackContentWidget {
        qproperty-darkerColor: rgb( 45, 50, 57 );
        qproperty-lighterColor: rgb( 54, 61, 68 );
        qproperty-gridColor: rgba( 128, 128, 128, 84 );
        qproperty-embossColor: rgba( 0, 0, 0, 0 );
}
```

**Comment by RebeccaDeField** [comment] 2015-11-19 04:00
close #2

**Closed as completed** 2016-01-04 00:03 UTC
Labels: help wanted
